### ISSUE TITLE
AWS::Serverless::LayerVersion not supported in eu-north-1

### ISSUE THREAD

**Issue by pahud** [pahud/lambda-layer-kubectl#4]
```
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LayerName:
    Type: String
Transform: AWS::Serverless-2016-10-31
Description: Create a Layer
Resources:
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Ref: LayerName
      ContentUri: s3://.....
      CompatibleRuntimes:
      - provided
      LicenseInfo: Available under the MIT-0 license.
      RetentionPolicy: Retain
Outputs:
  LayerVersionArn:
    Description: ARN for the published Layer version
    Value:
      Ref: LambdaLayer
    Export:
      Name:
        Fn::Sub: LayerVersionArn-${AWS::StackName}
```
cloudformation console complains 

```
Template format error: Unrecognized resource types: [AWS::Lambda::LayerVersion]. Rollback requested by user.
```

![image](https://user-images.githubusercontent.com/278432/52991878-88916e00-3449-11e9-9a4a-97ed198f565d.png)
